[project]
name = "vrchat-autoban"
version = "0.1.0"
description = "Add your description here"
dependencies = [
    "vrchatapi>=1.18.1",
    "loguru>=0.7.2",
    "tqdm>=4.66.5",
    "pendulum>=3.0.0",
    "pydantic>=2.8.2",
    "aiofiles>=24.1.0",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
  "mypy==1.6.1",
  "types-requests>=2.31.0.4",
  "pylint>=2.17.5",
  "autopep8>=2.0.4",
  "black>=23.9.1",
  "pylance>=0.7.5",
  "pyright>=1.1.327",
  "flake8>=6.1.0",
  "types-tqdm==4.66.0.2",
  "pandas-stubs==2.1.1.230928",
  "mypy-extensions==1.0.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/vrchat_autoban"]
